# Generated by Django 4.2.14 on 2024-07-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='images/album'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(upload_to='images/album'),
        ),
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(upload_to='media/files/music'),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(upload_to='images/music'),
        ),
    ]
